name: etc
favicon: null
layout_spectrum: 1
typography_spectrum: 0.98324
title: etc - interactive opus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#89bedd'
    - '#dbeaf4'
    - '#aacfe6'
    - '#c1dced'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
